In [37]:
import pandas as pd

### 1. Read a .csv from an url w Pandas
#### Target site: https://www.football-data.co.uk/data.php

In [38]:
# reading the csv file
url='https://www.football-data.co.uk/mmz4281/2526/E0.csv'
df_epl=pd.read_csv(url)

In [39]:
# FTHG & FTAG terms are confusing, while they just mean 
# final time home goals and aways goals
df_epl.rename(columns={'FTHG':'home_goals', 
                          'FTAG':'away_goals'}, inplace=True)
df_epl

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

### 2. Working with multiple .csv files

In [40]:
# now we read multiple csvs and add them to a list
# for that we need a root url
root="https://www.football-data.co.uk/mmz4281/"

leagues=['E0', 'E1', 'E2']

In [41]:
# now we loop thru the legues array and read the corresponding csvs
frames=[]
for league in leagues:
    df=pd.read_csv(root+'2526/'+league+'.csv')
    frames.append(df)

In [42]:
#check the length of "frames"
len(frames)

3

In [43]:
frames[1]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E1,08/08/2025,20:00,Birmingham,Ipswich,1,1,D,0,0,...,1.88,1.98,1.81,2.12,1.88,1.98,1.81,1.94,1.90,2.10
1,E1,09/08/2025,12:30,Charlton,Watford,1,0,H,0,0,...,1.95,1.90,1.95,1.95,1.95,1.90,1.86,1.83,2.03,1.95
2,E1,09/08/2025,12:30,Coventry,Hull,0,0,D,0,0,...,1.88,1.98,1.95,1.95,1.91,1.98,1.87,1.82,1.97,2.01
3,E1,09/08/2025,12:30,Southampton,Wrexham,2,1,H,0,1,...,1.90,1.95,1.75,2.18,1.90,1.95,1.84,1.91,1.92,2.07
4,E1,09/08/2025,15:00,Middlesbrough,Swansea,1,0,H,0,0,...,2.05,1.75,2.00,1.91,2.05,1.82,2.00,1.76,2.16,1.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E1,02/05/2026,12:30,Preston,Southampton,1,3,A,0,1,...,1.93,1.93,NaN,NaN,2.00,1.93,1.88,1.84,NaN,NaN
548,E1,02/05/2026,12:30,Sheffield Weds,West Brom,2,1,H,2,0,...,2.00,1.85,NaN,NaN,2.00,1.90,1.93,1.82,NaN,NaN
549,E1,02/05/2026,12:30,Swansea,Charlton,3,1,H,0,0,...,1.78,2.03,NaN,NaN,1.78,2.10,1.73,2.02,NaN,NaN
550,E1,02/05/2026,12:30,Watford,Coventry,0,4,A,0,2,...,1.73,2.08,NaN,NaN,1.81,2.08,1.75,2.00,NaN,NaN
551,E1,02/05/2026,12:30,Wrexham,Middlesbrough,2,2,D,2,2,...,1.95,1.90,NaN,NaN,1.96,1.90,1.91,1.83,NaN,NaN

In [44]:
for df in frames:
    df.rename(columns={'FTHG':'home_goals', 
                          'FTAG':'away_goals'}, inplace=True)

frames[1]

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E1,08/08/2025,20:00,Birmingham,Ipswich,1,1,D,0,0,...,1.88,1.98,1.81,2.12,1.88,1.98,1.81,1.94,1.90,2.10
1,E1,09/08/2025,12:30,Charlton,Watford,1,0,H,0,0,...,1.95,1.90,1.95,1.95,1.95,1.90,1.86,1.83,2.03,1.95
2,E1,09/08/2025,12:30,Coventry,Hull,0,0,D,0,0,...,1.88,1.98,1.95,1.95,1.91,1.98,1.87,1.82,1.97,2.01
3,E1,09/08/2025,12:30,Southampton,Wrexham,2,1,H,0,1,...,1.90,1.95,1.75,2.18,1.90,1.95,1.84,1.91,1.92,2.07
4,E1,09/08/2025,15:00,Middlesbrough,Swansea,1,0,H,0,0,...,2.05,1.75,2.00,1.91,2.05,1.82,2.00,1.76,2.16,1.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E1,02/05/2026,12:30,Preston,Southampton,1,3,A,0,1,...,1.93,1.93,NaN,NaN,2.00,1.93,1.88,1.84,NaN,NaN
548,E1,02/05/2026,12:30,Sheffield Weds,West Brom,2,1,H,2,0,...,2.00,1.85,NaN,NaN,2.00,1.90,1.93,1.82,NaN,NaN
549,E1,02/05/2026,12:30,Swansea,Charlton,3,1,H,0,0,...,1.78,2.03,NaN,NaN,1.78,2.10,1.73,2.02,NaN,NaN
550,E1,02/05/2026,12:30,Watford,Coventry,0,4,A,0,2,...,1.73,2.08,NaN,NaN,1.81,2.08,1.75,2.00,NaN,NaN
551,E1,02/05/2026,12:30,Wrexham,Middlesbrough,2,2,D,2,2,...,1.95,1.90,NaN,NaN,1.96,1.90,1.91,1.83,NaN,NaN

#### Multiple seasons

In [45]:
frames=[]
for league in leagues:
    for season in range(20,26):
        df=pd.read_csv(root+str(season)+str(season+1)+'/'+league+'.csv', encoding='unicode_escape')
        df['season']=season
        frames.append(df)

C:\Users\abirl\AppData\Local\Temp\ipykernel_16756\1897552581.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['season']=season

In [46]:
len(frames)

18

### 3. Organize all the data in a  dictionary

In [47]:
dict_countries={'La Liga':'SP1', 'Spanish Segunda Div':'SP2',
                'Bundesliga':'D1',
                'EPL':'E0', 'Eng League 1':'E1'}

In [48]:
dict_historical_data={}

# looping thru keys and creating list of leagues

frames=[]

for league in dict_countries:
    for season in range(20,26):
        df=pd.read_csv(root+str(season)+str(season+1)+'/'+dict_countries[league]+'.csv', encoding='unicode_escape')
        df.insert(1, 'Season', season)
        frames.append(df)
    # here we create frame for each league and add it to the dictionary with the league name as key
    df_net=pd.concat(frames)
    dict_historical_data[league]=df_net

C:\Users\abirl\AppData\Local\Temp\ipykernel_16756\1232805658.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, 'Season', season)

In [49]:
dict_historical_data['La Liga']

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP1,20,12/09/2020,15:00,Eibar,Celta,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,20,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,20,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,20,13/09/2020,13:00,Alaves,Betis,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,20,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,NaN,25,23/05/2026,20:00,Girona,Elche,1,1,D,0,...,3.95,1.75,3.80,4.40,1.80,3.8,4.20,1.80,3.75,4.20
376,NaN,25,23/05/2026,20:00,Mallorca,Oviedo,3,0,H,1,...,6.50,1.45,4.33,7.50,1.48,4.4,6.50,1.48,4.40,6.50
377,NaN,25,23/05/2026,20:00,Real Madrid,Ath Bilbao,4,2,H,2,...,5.20,1.53,4.60,5.50,1.55,4.8,5.00,1.55,4.60,5.00
378,NaN,25,23/05/2026,20:00,Valencia,Barcelona,3,1,H,0,...,1.87,3.40,4.10,1.93,3.40,4.0,1.95,3.30,4.00,1.95
379,NaN,25,24/05/2026,20:00,Villarreal,Ath Madrid,5,1,H,4,...,2.45,NaN,NaN,NaN,NaN,NaN,NaN,2.40,3.80,2.60

### Filter dataframe based on a condition

In [50]:
df_epl[df_epl['HomeTeam']=="Man City"]

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
11,E0,23/08/2025,12:30,Man City,Tottenham,0,2,A,0,2,...,1.87,1.87,1.83,2.11,1.87,2.09,1.81,1.95,1.94,2.04
39,E0,14/09/2025,16:30,Man City,Man United,3,0,H,1,0,...,2.03,1.83,2.32,1.68,2.10,1.83,2.03,1.77,2.13,1.86
54,E0,27/09/2025,15:00,Man City,Burnley,5,1,H,1,1,...,1.95,1.90,2.03,1.88,1.95,1.98,1.88,1.89,2.05,1.92
74,E0,18/10/2025,15:00,Man City,Everton,2,0,H,0,0,...,2.05,1.80,2.03,1.90,2.05,1.93,1.93,1.85,2.10,1.89
98,E0,02/11/2025,16:30,Man City,Bournemouth,3,1,H,2,1,...,1.85,2.00,1.91,2.01,1.85,2.02,1.80,1.97,1.95,2.03
109,E0,09/11/2025,16:30,Man City,Liverpool,3,0,H,2,0,...,1.83,2.03,1.94,1.98,1.93,2.03,1.86,1.91,1.94,2.05
121,E0,29/11/2025,15:00,Man City,Leeds,3,2,H,2,0,...,1.83,2.03,1.87,2.04,1.83,2.03,1.79,1.99,1.90,2.09
143,E0,06/12/2025,15:00,Man City,Sunderland,3,0,H,2,0,...,1.95,1.90,1.99,1.92,1.95,1.97,1.86,1.91,2.02,1.94
163,E0,20/12/2025,15:00,Man City,West Ham,3,0,H,2,0,...,1.98,1.88,1.97,1.93,1.98,2.04,1.86,1.93,2.04,1.95
199,E0,04/01/2026,17:30,Man City,Chelsea,1,1,D,1,0,...,2.00,1.85,2.02,1.91,2.00,1.90,1.93,1.84,2.04,1.95
206,E0,07/01/2026,19:30,Man City,Brighton,1,1,D,1,0,...,1.80,2.05,1.87,2.06,1.83,2.12,1.75,2.05,1.91,2.08
223,E0,24/01/2026,15:00,Man City,Wolves,2,0,H,2,0,...,1.88,1.98,NaN,NaN,1.90,2.00,1.82,1.91,1.92,2.07
256,E0,11/02/2026,19:30,Man City,Fulham,3,0,H,3,0,...,2.03,1.78,NaN,NaN,2.05,1.87,1.97,1.77,2.11,1.87
265,E0,21/02/2026,20:00,Man City,Newcastle,2,1,H,2,1,...,1.93,1.93,NaN,NaN,1.93,1.98,1.83,1.95,1.92,2.05
288,E0,04/03/2026,19:30,Man City,Nott'm Forest,2,2,D,1,0,...,1.95,1.90,NaN,NaN,1.95,2.00,1.85,1.92,1.96,2.00
327,E0,19/04/2026,16:30,Man City,Arsenal,2,1,H,1,1,...,1.85,2.00,NaN,NaN,1.85,2.00,1.78,1.93,1.91,2.09
353,E0,09/05/2026,17:30,Man City,Brentford,3,0,H,0,0,...,1.98,1.88,NaN,NaN,1.98,1.96,1.89,1.84,2.04,1.95
359,E0,13/05/2026,20:00,Man City,Crystal Palace,3,0,H,2,0,...,1.88,1.98,NaN,NaN,1.88,2.00,1.80,1.93,1.96,2.02
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09

In [51]:
len(df_epl[df_epl['HomeTeam']=="Man City"])

19

In [59]:
# we can also find the number of home matches played by
# man city, and chelsea like this:-

df_epl[(df_epl['HomeTeam']=="Man City") | (df_epl['HomeTeam']=="Chelsea")].value_counts('HomeTeam')

HomeTeam
Chelsea     19
Man City    19
Name: count, dtype: int64

### Create column based on 1 conditions: np.where()

In [60]:
import numpy as np

# create an array based on AvgCAHH greater than 1.92

np.where(df_epl['AvgCAHH']>=1.92, 'High', 'Low')

array(['High', 'High', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low',
       'Low', 'Low', 'Low', 'High', 'High', 'High', 'Low', 'High', 'High',
       'High', 'Low', 'High', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low',
       'Low', 'High', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low',
       'High', 'High', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'Low',
       'High', 'Low', 'High', 'Low', 'High', 'Low', 'High', 'High', 'Low',
       'Low', 'High', 'Low', 'Low', 'Low', 'Low', 'Low', 'High', 'Low',
       'Low', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'Low', 'Low',
       'High', 'Low', 'High', 'High', 'High', 'Low', 'Low', 'Low', 'High',
       'Low', 'High', 'High', 'High', 'Low', 'High', 'High', 'Low', 'Low',
       'Low', 'Low', 'High', 'High', 'High', 'Low', 'High', 'Low', 'Low',
       'Low', 'Low', 'High', 'Low', 'High', 'High', 'High', 'High',
       'High', 'Low', 'Low', 'Low', 'Low', 'Low', 'High', 'High', 'Low',
       'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'High',
       'High', 'High', 'High', 'Low', 'Low', 'Low', 'High', 'Low', 'High',
       'Low', 'Low', 'Low', 'Low', 'High', 'Low', 'Low', 'High', 'Low',
       'Low', 'Low', 'Low', 'Low', 'High', 'Low', 'High', 'Low', 'High',
       'Low', 'Low', 'Low', 'Low', 'High', 'High', 'Low', 'High', 'High',
       'High', 'Low', 'Low', 'High', 'Low', 'Low', 'High', 'High', 'Low',
       'Low', 'Low', 'Low', 'High', 'High', 'Low', 'Low', 'High', 'High',
       'Low', 'Low', 'Low', 'Low', 'High', 'Low', 'Low', 'Low', 'Low',
       'Low', 'Low', 'Low', 'High', 'Low', 'High', 'High', 'High', 'Low',
       'Low', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'Low', 'Low',
       'Low', 'Low', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'High',
       'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low',
       'Low', 'Low', 'Low', 'Low', 'Low', 'High', 'Low', 'Low', 'Low',
       'High', 'High', 'High', 'Low', 'Low', 'High', 'Low', 'Low', 'High',
       'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low',
       'High', 'Low', 'High', 'Low', 'High', 'High', 'Low', 'Low', 'High',
       'Low', 'Low', 'High', 'Low', 'High', 'Low', 'Low', 'Low', 'High',
       'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'High', 'Low',
       'High', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'High',
       'Low', 'Low', 'Low', 'Low', 'High', 'Low', 'Low', 'Low', 'High',
       'Low', 'Low', 'High', 'Low', 'Low', 'Low', 'High', 'Low', 'High',
       'High', 'High', 'High', 'High', 'Low', 'Low', 'Low', 'Low', 'Low',
       'High', 'High', 'High', 'Low', 'Low', 'Low', 'Low', 'High', 'Low',
       'Low', 'High', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'Low',
       'Low', 'Low', 'High', 'Low', 'High', 'Low', 'Low', 'Low', 'Low',
       'High', 'Low', 'Low', 'Low', 'High', 'High', 'Low', 'Low', 'High',
       'High', 'High', 'Low', 'Low', 'High', 'High', 'High', 'Low', 'Low',
       'Low', 'High', 'Low', 'Low', 'Low', 'Low', 'High', 'High', 'Low',
       'High', 'Low', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'Low',
       'Low', 'Low', 'Low'], dtype='<U4')

In [55]:
# set it to a new column
df_epl['AvgCAHH_tier']=np.where(df_epl['AvgCAHH']>=1.92, 'High', 'Low')

df_epl

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,AvgCAHH_tier
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86,High
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86,High
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08,Low
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97,Low
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09,Low
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04,Low
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12,Low
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03,Low
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01,Low

In [56]:
df_epl.value_counts('AvgCAHH_tier')

AvgCAHH_tier
Low     252
High    128
Name: count, dtype: int64

### Creating column from more than 2 choices: np.select()

In [65]:
conditions=[
    df_epl['AvgCAHH']>=2,
    (df_epl['AvgCAHH']<2) & (df_epl['AvgCAHH']>=1.8),
    df_epl['AvgCAHH']<1.8
]

values= ['High', 'Mid', 'Low']

In [67]:
df_epl['AvgCAHH_score']= np.select(conditions, values, default='Unknown')

C:\Users\abirl\AppData\Local\Temp\ipykernel_16756\1867696189.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_epl['AvgCAHH_score']= np.select(conditions, values, default='Unknown')

#### isin: single filtering

In [68]:
df_epl[df_epl['HomeTeam'].isin(['Man City', 'Chelsea'])].value_counts('HomeTeam')

HomeTeam
Chelsea     19
Man City    19
Name: count, dtype: int64